import React, {useState} from 'react'
import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from "axios";

const Home: NextPage = () => {
    const [authorised, setAuthorised] = useState<Boolean>(false)

    const authWithTwitter = async () => {
        const data = {
            oauth_callback: 'http://localhost:3000',
            x_auth_access_type: 'read',
        }
        fetch("/auth")
        axios.post('https://api.twitter.com/oauth/request_token', )
            .then((response) => {
                console.log(response);
                setAuthorised(true)
            })
            .catch((err: any) => console.log('err', err.message));
    }

    const signOffTwitter = async () => {
        console.log('signing off')

        setAuthorised(false)
    }


    return (
        <div className={styles.container}>
            <Head>
                <title>Twitter Auth</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Twitter Auth
                </h1>

                {!!authorised ? <button onClick={signOffTwitter}>Sign out from Twitter</button> :
                    <div onClick={authWithTwitter}><img src="twitter-sign-in.png" /></div>}

            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
                </a>
            </footer>
        </div>
    )
}

export default Home
