import React, { useEffect } from "react";
import type { NextPage } from "next";
import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";

const Home: NextPage = () => {
	const { data: session } = useSession();

	useEffect(() => console.log(session), [session]);

	return (
		<div className={styles.container}>
			<Head>
				<title>Twitter Auth</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Twitter Auth</h1>

				{!!session ? (
					<div style={{ textAlign: "center" }}>
						<p>Signed in as {session?.user?.name}</p>
						<button onClick={async () => await signOut()}>
							Sign out from Twitter
						</button>
					</div>
				) : (
					<div onClick={async () => await signIn("twitter")}>
						<Image
							src="/twitter-sign-in.png"
							width={158}
							height={28}
							alt={"twitter sign in button"}
						/>
					</div>
				)}
			</main>
		</div>
	);
};

export default Home;
